/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/tablets/{dispositivo_id}/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Emitir Token Tablet
         * @description Provisionamento do totem: um admin emite o token uma vez, na bancada.
         *
         *     O token carrega o `ponto_id` — é isso que impede um tablet de operar em
         *     um ponto de acesso que não é o dele.
         */
        post: operations["emitir_token_tablet_api_v1_auth_tablets__dispositivo_id__token_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/identificacao": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Identificar */
        post: operations["identificar_api_v1_identificacao_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pessoas/{pessoa_id}/consentimento": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Registrar Consentimento
         * @description LGPD art. 11: biometria exige consentimento específico e destacado.
         *
         *     Sem um registro vigente aqui, o cadastro biométrico é recusado.
         */
        post: operations["registrar_consentimento_api_v1_pessoas__pessoa_id__consentimento_post"];
        /**
         * Revogar Consentimento
         * @description Revogação elimina os vetores — não apenas marca uma flag.
         *
         *     A LGPD garante eliminação do dado após revogação (art. 18). Manter o
         *     embedding "por garantia" descumpriria isso.
         */
        delete: operations["revogar_consentimento_api_v1_pessoas__pessoa_id__consentimento_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pessoas/{pessoa_id}/biometrias": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cadastrar Biometria
         * @description Cadastre 3 a 5 capturas por pessoa, em ângulos e luzes diferentes.
         *
         *     Melhora o recall sem precisar afrouxar o limiar de distância — que é o
         *     ajuste que costuma ser feito por engano e que dispara o falso positivo.
         */
        post: operations["cadastrar_biometria_api_v1_pessoas__pessoa_id__biometrias_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/verificacoes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar */
        get: operations["listar_api_v1_verificacoes_get"];
        put?: never;
        /**
         * Abrir Verificacao
         * @description 202, não 200 — e isso é decisão de projeto, não detalhe.
         *
         *     A verificação ainda não terminou: ela depende de uma resposta assíncrona
         *     vinda da borda. O tablet recebe o id e aguarda o desfecho no WebSocket.
         *     Fazer este endpoint bloquear até a Raspberry responder acoplaria um
         *     request HTTP à latência da inferência e derrubaria tudo quando a Pi
         *     travasse.
         */
        post: operations["abrir_verificacao_api_v1_verificacoes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/verificacoes/{verificacao_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obter */
        get: operations["obter_api_v1_verificacoes__verificacao_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/evidencias": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Enviar */
        post: operations["enviar_api_v1_evidencias_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pontos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar Pontos */
        get: operations["listar_pontos_api_v1_pontos_get"];
        put?: never;
        /** Criar Ponto */
        post: operations["criar_ponto_api_v1_pontos_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dispositivos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar Dispositivos
         * @description Presença ao vivo, sem polling.
         *
         *     A coluna `online` é mantida pelo worker a partir do status retido e do
         *     Last Will de cada dispositivo. O broker é quem avisa que alguém morreu.
         */
        get: operations["listar_dispositivos_api_v1_dispositivos_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pontos/{ponto_id}/liberacao-manual": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Liberacao Manual
         * @description Override do supervisor — SEMPRE auditado.
         *
         *     Um sistema de controle de acesso sem escape manual trava a operação no
         *     primeiro defeito de câmera. Um escape manual sem trilha de auditoria
         *     vira o caminho preferido para burlar o controle. Por isso os dois
         *     andam juntos: a justificativa é obrigatória e fica gravada.
         */
        post: operations["liberacao_manual_api_v1_pontos__ponto_id__liberacao_manual_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pessoas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar */
        get: operations["listar_api_v1_pessoas_get"];
        put?: never;
        /** Criar */
        post: operations["criar_api_v1_pessoas_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pessoas/{pessoa_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obter */
        get: operations["obter_api_v1_pessoas__pessoa_id__get"];
        put?: never;
        post?: never;
        /**
         * Desativar
         * @description Desativa a pessoa, sem apagar o histórico.
         *
         *     Apagar a linha levaria junto as verificações dela — e histórico de acesso
         *     é registro de auditoria de segurança do trabalho, que precisa sobreviver
         *     ao desligamento do funcionário.
         *
         *     Para eliminar o dado biométrico, o caminho é revogar o consentimento:
         *     `DELETE /pessoas/{id}/consentimento` apaga os vetores de verdade.
         */
        delete: operations["desativar_api_v1_pessoas__pessoa_id__delete"];
        options?: never;
        head?: never;
        /** Atualizar */
        patch: operations["atualizar_api_v1_pessoas__pessoa_id__patch"];
        trace?: never;
    };
    "/api/v1/tipos-epi": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar Tipos */
        get: operations["listar_tipos_api_v1_tipos_epi_get"];
        put?: never;
        /**
         * Criar Tipo
         * @description O `codigo` é o que trafega no MQTT e o que a borda devolve.
         *
         *     Precisa bater exatamente com o identificador que o app e a Raspberry
         *     usam — item com código desconhecido é descartado em silêncio do outro
         *     lado. O `classe_modelo` é o nome da classe na saída do modelo treinado.
         */
        post: operations["criar_tipo_api_v1_tipos_epi_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pontos/{ponto_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Atualizar Ponto */
        patch: operations["atualizar_ponto_api_v1_pontos__ponto_id__patch"];
        trace?: never;
    };
    "/api/v1/pontos/{ponto_id}/epis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Definir Epis Exigidos
         * @description Define a lista completa de EPIs exigidos no ponto.
         *
         *     É PUT e não PATCH de propósito: a lista enviada substitui a anterior
         *     inteira. Assim o painel manda o estado final que o operador vê na tela,
         *     sem precisar calcular o que foi adicionado e o que foi removido.
         *
         *     Este endpoint é o que torna verdadeira a promessa de que mudar a
         *     exigência de um ponto não exige tocar em código nem reprogramar
         *     dispositivo — a Raspberry recebe a lista nova no próximo cmd/capturar.
         */
        put: operations["definir_epis_exigidos_api_v1_pontos__ponto_id__epis_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/relatorios/conformidade": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Conformidade
         * @description Taxa de aprovação por ponto no período.
         */
        get: operations["conformidade_api_v1_relatorios_conformidade_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/relatorios/epis-faltantes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Epis Faltantes
         * @description EPI mais esquecido por ponto — o relatório que vira ação de treinamento.
         */
        get: operations["epis_faltantes_api_v1_relatorios_epis_faltantes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/relatorios/biometria": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Desempenho Biometria
         * @description Desempenho da identificação facial em campo.
         *
         *     É o dado que permite calibrar FACE_DISTANCIA_MAX com evidência em vez de
         *     com chute — e rende um capítulo inteiro de resultados no TCC.
         */
        get: operations["desempenho_biometria_api_v1_relatorios_biometria_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Inclui o estado do broker de propósito.
         *
         *     Sem MQTT o sistema não abre catraca nenhuma — reportar "saudável" nesse
         *     estado seria mentira útil para ninguém.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BiometriaIn */
        BiometriaIn: {
            /** Modelo */
            modelo: string;
            /** Embedding */
            embedding: number[];
            /** Qualidade */
            qualidade?: number | null;
        };
        /** Body_enviar_api_v1_evidencias_post */
        Body_enviar_api_v1_evidencias_post: {
            /**
             * Verificacao Id
             * Format: uuid
             */
            verificacao_id: string;
            /**
             * Rosto Borrado
             * @default true
             */
            rosto_borrado: boolean;
            /**
             * Arquivo
             * Format: binary
             */
            arquivo: string;
        };
        /** ConsentimentoIn */
        ConsentimentoIn: {
            /** Versao Termo */
            versao_termo: string;
            /**
             * Finalidade
             * @default Identificação do trabalhador para verificação de uso de EPI no controle de acesso.
             */
            finalidade: string;
        };
        /** DeteccaoOut */
        DeteccaoOut: {
            /** Epi */
            epi: string;
            /** Rotulo */
            rotulo: string;
            /** Presente */
            presente: boolean;
            /** Confianca */
            confianca: number;
            /** Frames Confirmados */
            frames_confirmados: number | null;
        };
        /** DispositivoOut */
        DispositivoOut: {
            /** Id */
            id: number;
            /** Ponto Id */
            ponto_id: number;
            /** Tipo */
            tipo: string;
            /** Client Id Mqtt */
            client_id_mqtt: string;
            /** Online */
            online: boolean;
            /** Visto Em */
            visto_em: string | null;
            /** Firmware */
            firmware: string | null;
            /** Versao Modelo */
            versao_modelo: string | null;
        };
        /**
         * EpisExigidosIn
         * @description Lista COMPLETA de códigos exigidos; substitui a anterior.
         */
        EpisExigidosIn: {
            /** Codigos */
            codigos: string[];
        };
        /** EvidenciaOut */
        EvidenciaOut: {
            /** Evidencia Id */
            evidencia_id: string;
            /**
             * Expira Em
             * Format: date-time
             */
            expira_em: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * IdentificacaoIn
         * @description O tablet envia APENAS o vetor. A imagem do rosto não sai do tablet.
         */
        IdentificacaoIn: {
            /** Ponto Id */
            ponto_id: number;
            /**
             * Modelo
             * @description Identificador do modelo que gerou o embedding. Embeddings de modelos diferentes não são comparáveis.
             */
            modelo: string;
            /**
             * Embedding
             * @description Vetor FaceNet. Dimensão esperada: 512.
             */
            embedding: number[];
        };
        /** IdentificacaoOut */
        IdentificacaoOut: {
            /** Identificacao Id */
            identificacao_id: string | null;
            /** Resultado */
            resultado: string;
            /** Pessoa Id */
            pessoa_id?: number | null;
            /** Nome */
            nome?: string | null;
            /** Distancia */
            distancia?: number | null;
            /** Expira Em */
            expira_em?: string | null;
        };
        /** LiberacaoManualIn */
        LiberacaoManualIn: {
            /**
             * Verificacao Id
             * Format: uuid
             */
            verificacao_id: string;
            /** Justificativa */
            justificativa: string;
        };
        /** LoginIn */
        LoginIn: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Senha */
            senha: string;
        };
        /** PaginaPessoas */
        PaginaPessoas: {
            /** Total */
            total: number;
            /** Itens */
            itens: components["schemas"]["PessoaOut"][];
        };
        /** PaginaVerificacoes */
        PaginaVerificacoes: {
            /** Total */
            total: number;
            /** Itens */
            itens: components["schemas"]["VerificacaoOut"][];
        };
        /** PessoaDetalhe */
        PessoaDetalhe: {
            /** Id */
            id: number;
            /** Matricula */
            matricula: string | null;
            /** Nome */
            nome: string;
            /** Funcao */
            funcao: string | null;
            /** Ativo */
            ativo: boolean;
            /** Biometrias */
            biometrias: number;
            /** Consentimento Vigente */
            consentimento_vigente: boolean;
            /**
             * Criado Em
             * Format: date-time
             */
            criado_em: string;
            /** Total Verificacoes */
            total_verificacoes: number;
            /** Ultima Verificacao */
            ultima_verificacao: string | null;
        };
        /** PessoaIn */
        PessoaIn: {
            /** Nome */
            nome: string;
            /** Funcao */
            funcao?: string | null;
            /** Matricula */
            matricula?: string | null;
            /**
             * Ativo
             * @default true
             */
            ativo: boolean;
        };
        /** PessoaOut */
        PessoaOut: {
            /** Id */
            id: number;
            /** Matricula */
            matricula: string | null;
            /** Nome */
            nome: string;
            /** Funcao */
            funcao: string | null;
            /** Ativo */
            ativo: boolean;
            /** Biometrias */
            biometrias: number;
            /** Consentimento Vigente */
            consentimento_vigente: boolean;
        };
        /** PessoaPatch */
        PessoaPatch: {
            /** Nome */
            nome?: string | null;
            /** Funcao */
            funcao?: string | null;
            /** Matricula */
            matricula?: string | null;
            /** Ativo */
            ativo?: boolean | null;
        };
        /** PontoIn */
        PontoIn: {
            /** Site Id */
            site_id: number;
            /** Codigo */
            codigo: string;
            /** Nome */
            nome: string;
            /**
             * Ativo
             * @default true
             */
            ativo: boolean;
        };
        /** PontoOut */
        PontoOut: {
            /** Id */
            id: number;
            /** Codigo */
            codigo: string;
            /** Nome */
            nome: string;
            /** Ativo */
            ativo: boolean;
            /**
             * Site Codigo
             * @default
             */
            site_codigo: string;
            /**
             * Epis Exigidos
             * @default []
             */
            epis_exigidos: string[];
        };
        /** PontoPatch */
        PontoPatch: {
            /** Nome */
            nome?: string | null;
            /** Ativo */
            ativo?: boolean | null;
        };
        /**
         * StatusVerificacao
         * @enum {string}
         */
        StatusVerificacao: "AGUARDANDO_ANALISE" | "APROVADA" | "REPROVADA" | "EXPIRADA" | "ERRO";
        /** TipoEpiIn */
        TipoEpiIn: {
            /**
             * Codigo
             * @description o que trafega no MQTT; precisa bater com o identificador usado no app e na borda
             */
            codigo: string;
            /** Rotulo */
            rotulo: string;
            /**
             * Classe Modelo
             * @description nome da classe na saída do modelo
             */
            classe_modelo: string;
        };
        /** TipoEpiOut */
        TipoEpiOut: {
            /** Id */
            id: number;
            /** Codigo */
            codigo: string;
            /** Rotulo */
            rotulo: string;
            /** Classe Modelo */
            classe_modelo: string;
        };
        /** TokenOut */
        TokenOut: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            /**
             * Expira Em
             * Format: date-time
             */
            expira_em: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * VerificacaoIn
         * @description O tablet NÃO informa pessoa_id.
         *
         *     Ele apresenta o token devolvido por /identificacao; o servidor resolve a
         *     pessoa a partir dele. Um tablet comprometido não consegue abrir
         *     verificação em nome de terceiros.
         */
        VerificacaoIn: {
            /** Ponto Id */
            ponto_id: number;
            /** Identificacao Id */
            identificacao_id?: string | null;
        };
        /** VerificacaoOut */
        VerificacaoOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Ponto Id */
            ponto_id: number;
            /** Status */
            status: string;
            /** Pessoa Id */
            pessoa_id: number | null;
            /** Pessoa Nome */
            pessoa_nome: string | null;
            /**
             * Iniciada Em
             * Format: date-time
             */
            iniciada_em: string;
            /** Concluida Em */
            concluida_em: string | null;
            /**
             * Expira Em
             * Format: date-time
             */
            expira_em: string;
            /** Latencia Ms */
            latencia_ms: number | null;
            /** Versao Modelo */
            versao_modelo: string | null;
            /** Motivo Falha */
            motivo_falha: string | null;
            /**
             * Deteccoes
             * @default []
             */
            deteccoes: components["schemas"]["DeteccaoOut"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    emitir_token_tablet_api_v1_auth_tablets__dispositivo_id__token_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dispositivo_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    identificar_api_v1_identificacao_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IdentificacaoIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IdentificacaoOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    registrar_consentimento_api_v1_pessoas__pessoa_id__consentimento_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pessoa_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConsentimentoIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revogar_consentimento_api_v1_pessoas__pessoa_id__consentimento_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pessoa_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cadastrar_biometria_api_v1_pessoas__pessoa_id__biometrias_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pessoa_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BiometriaIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_api_v1_verificacoes_get: {
        parameters: {
            query?: {
                ponto_id?: number | null;
                pessoa_id?: number | null;
                situacao?: components["schemas"]["StatusVerificacao"] | null;
                desde?: string | null;
                ate?: string | null;
                limite?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginaVerificacoes"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    abrir_verificacao_api_v1_verificacoes_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerificacaoIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerificacaoOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    obter_api_v1_verificacoes__verificacao_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                verificacao_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerificacaoOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    enviar_api_v1_evidencias_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_enviar_api_v1_evidencias_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenciaOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_pontos_api_v1_pontos_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PontoOut"][];
                };
            };
        };
    };
    criar_ponto_api_v1_pontos_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PontoIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PontoOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_dispositivos_api_v1_dispositivos_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DispositivoOut"][];
                };
            };
        };
    };
    liberacao_manual_api_v1_pontos__ponto_id__liberacao_manual_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ponto_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LiberacaoManualIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_api_v1_pessoas_get: {
        parameters: {
            query?: {
                /** @description filtra por nome ou matrícula */
                busca?: string | null;
                ativo?: boolean | null;
                /** @description true = só quem já tem rosto cadastrado */
                com_biometria?: boolean | null;
                limite?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginaPessoas"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    criar_api_v1_pessoas_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PessoaIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PessoaOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    obter_api_v1_pessoas__pessoa_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pessoa_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PessoaDetalhe"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    desativar_api_v1_pessoas__pessoa_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pessoa_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    atualizar_api_v1_pessoas__pessoa_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pessoa_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PessoaPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PessoaOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_tipos_api_v1_tipos_epi_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TipoEpiOut"][];
                };
            };
        };
    };
    criar_tipo_api_v1_tipos_epi_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TipoEpiIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TipoEpiOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    atualizar_ponto_api_v1_pontos__ponto_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ponto_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PontoPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PontoOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    definir_epis_exigidos_api_v1_pontos__ponto_id__epis_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ponto_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EpisExigidosIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PontoOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    conformidade_api_v1_relatorios_conformidade_get: {
        parameters: {
            query?: {
                dias?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    epis_faltantes_api_v1_relatorios_epis_faltantes_get: {
        parameters: {
            query?: {
                dias?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    desempenho_biometria_api_v1_relatorios_biometria_get: {
        parameters: {
            query?: {
                dias?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
}
